packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  "@fluxta/cli": "^0.2.0"
  "@fluxta/sdk": "^0.1.2"
  "@tailwindcss/vite": "^4.1.18"
  "@types/node": "^22.18.12"
  "@types/react": "^19.2.8"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^5.1.2"
  obs-websocket-js: "^5.0.8"
  react: "^19.2.3"
  react-dom: "^19.2.3"
  shx: "^0.3.4"
  tailwindcss: "^4.1.18"
  tsdown: "^0.18.1"
  turbo: "^2.7.3"
  typescript: "^5.9.3"
  uuid: "^11.1.0"
  vitest: "^4.1.11"
  zod: "^4.4.3"

minimumReleaseAgeExclude:
  - '@fluxta/cli@0.2.0'
  - '@fluxta/sdk@0.1.2'
